#!/usr/bin/env python3
"""
Android Course API - Setup Wizard
Generates config.toml and service files from user input
"""

import os
import sys
from pathlib import Path

def banner():
    """Display welcome banner"""
    print("=" * 70)
    print("Android Course API - Setup Wizard")
    print("=" * 70)
    print()

def prompt(question, default=None):
    """Prompt user for input with optional default"""
    if default:
        response = input(f"{question} [{default}]: ").strip()
        return response if response else default
    else:
        response = input(f"{question}: ").strip()
        while not response:
            print("This field is required.")
            response = input(f"{question}: ").strip()
        return response

def yes_no(question, default="y"):
    """Ask a yes/no question"""
    valid = {"y": True, "yes": True, "n": False, "no": False}
    prompt_text = f"{question} [Y/n]: " if default == "y" else f"{question} [y/N]: "
    
    while True:
        response = input(prompt_text).strip().lower()
        if not response:
            return valid[default]
        if response in valid:
            return valid[response]
        print("Please answer 'y' or 'n'")

def main():
    banner()
    
    print("This wizard will help you configure the Android Course API.")
    print("You can press Enter to accept defaults shown in [brackets].")
    print()
    
    config = {}
    
    # Server configuration
    print("SERVER CONFIGURATION")
    print("-" * 70)
    config['base_url'] = prompt("Public URL for the API (e.g., https://server.edu/android)", 
                                "https://localhost/android")
    config['host'] = prompt("Flask bind address", "127.0.0.1")
    config['port'] = prompt("Flask port", "5000")
    config['workers'] = prompt("Number of gunicorn workers", "2")
    config['timeout'] = prompt("Request timeout (seconds)", "120")
    print()
    
    # Path configuration
    print("PATH CONFIGURATION")
    print("-" * 70)
    base_dir = prompt("Base directory for all data", "/var/www/android_course")
    config['upload_dir'] = prompt("Upload directory", f"{base_dir}/uploads")
    config['token_dir'] = prompt("Token directory", f"{base_dir}/tokens")
    config['log_dir'] = prompt("Log directory", f"{base_dir}/logs")
    print()
    
    # Storage configuration
    print("STORAGE CONFIGURATION")
    print("-" * 70)
    config['max_file_size_mb'] = prompt("Maximum file size (MB)", "50")
    config['student_quota_mb'] = prompt("Student quota (MB)", "500")
    config['rate_limit'] = prompt("Upload rate limit (per minute)", "10")
    config['allowed_extensions'] = prompt(
        "Allowed file extensions (comma-separated)",
        "txt,pdf,png,jpg,jpeg,gif,json,xml,csv,zip,mp3,mp4,doc,docx"
    )
    print()
    
    # Service configuration
    print("SERVICE CONFIGURATION")
    print("-" * 70)
    config['user'] = prompt("System user to run service", "installer")
    config['group'] = prompt("System group", "installer")
    config['working_dir'] = prompt("Service working directory", os.getcwd())
    config['python_path'] = prompt("Python executable path", "/usr/bin/python3")
    config['gunicorn_path'] = prompt("Gunicorn executable path", "/usr/bin/gunicorn")
    print()
    
    # Apache configuration
    print("APACHE CONFIGURATION")
    print("-" * 70)
    config['apache_conf_dir'] = prompt("Apache config directory", "/etc/httpd/conf.d")
    config['apache_location'] = prompt("Apache proxy location", "/android")
    config['max_request_body_mb'] = prompt("Max request body size (MB)", "52")
    print()
    
    # Security
    print("SECURITY")
    print("-" * 70)
    config['require_https'] = yes_no("Require HTTPS?", "y")
    config['enable_rate_limiting'] = yes_no("Enable rate limiting?", "y")
    print()
    
    # Logging
    print("LOGGING")
    print("-" * 70)
    log_levels = ["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"]
    print(f"Available log levels: {', '.join(log_levels)}")
    config['log_level'] = prompt("Log level", "INFO")
    print()
    
    # Generate config.toml
    print("=" * 70)
    print("GENERATING CONFIGURATION FILES")
    print("=" * 70)
    
    config_toml = f"""# Android Course API Configuration
# Generated by setup wizard
# DO NOT commit this file to version control!

[server]
base_url = "{config['base_url']}"
host = "{config['host']}"
port = {config['port']}
workers = {config['workers']}
timeout = {config['timeout']}

[paths]
upload_dir = "{config['upload_dir']}"
token_dir = "{config['token_dir']}"
log_dir = "{config['log_dir']}"

[storage]
max_file_size_mb = {config['max_file_size_mb']}
student_quota_mb = {config['student_quota_mb']}
rate_limit = {config['rate_limit']}
allowed_extensions = "{config['allowed_extensions']}"

[logging]
level = "{config['log_level']}"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

[security]
require_https = {str(config['require_https']).lower()}
enable_rate_limiting = {str(config['enable_rate_limiting']).lower()}

[service]
user = "{config['user']}"
group = "{config['group']}"
working_dir = "{config['working_dir']}"
python_path = "{config['python_path']}"
gunicorn_path = "{config['gunicorn_path']}"

[apache]
conf_dir = "{config['apache_conf_dir']}"
location = "{config['apache_location']}"
max_request_body_mb = {config['max_request_body_mb']}
"""
    
    # Write config.toml
    with open('config.toml', 'w') as f:
        f.write(config_toml)
    print(f"✓ Created config.toml")
    
    # Generate systemd service file
    service_file = f"""[Unit]
Description=Android Course File API
After=network.target

[Service]
User={config['user']}
Group={config['group']}
WorkingDirectory={config['working_dir']}
Environment="PATH={os.path.dirname(config['python_path'])}:/usr/local/bin:/usr/bin"
ExecStart={config['gunicorn_path']} --bind {config['host']}:{config['port']} --workers {config['workers']} --timeout {config['timeout']} --access-logfile {config['log_dir']}/access.log --error-logfile {config['log_dir']}/error.log app:app
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
"""
    
    with open('android-api.service', 'w') as f:
        f.write(service_file)
    print(f"✓ Created android-api.service")
    
    # Generate Apache config
    apache_conf = f"""# Android Course File API - Apache Reverse Proxy Configuration
# Add this to {config['apache_conf_dir']}/android-api.conf

# Proxy settings for Android Course API
<Location {config['apache_location']}>
    ProxyPass http://{config['host']}:{config['port']}
    ProxyPassReverse http://{config['host']}:{config['port']}
    
    # Allow larger uploads ({config['max_request_body_mb']}MB)
    LimitRequestBody {int(config['max_request_body_mb']) * 1024 * 1024}
</Location>

# Optional: Restrict to campus network only (if no VPN access needed)
# Uncomment if external access should be blocked
#<Location {config['apache_location']}>
#    Require ip 141.166.0.0/16
#    # Add VPN range if needed
#    # Require ip 10.0.0.0/8
#</Location>
"""
    
    with open('android-api.conf', 'w') as f:
        f.write(apache_conf)
    print(f"✓ Created android-api.conf")
    
    # Create directories
    print()
    if yes_no(f"Create directories ({config['upload_dir']}, {config['token_dir']}, {config['log_dir']})?", "y"):
        for directory in [config['upload_dir'], config['token_dir'], config['log_dir']]:
            Path(directory).mkdir(parents=True, exist_ok=True)
            print(f"✓ Created {directory}")
    
    # Create empty tokens file
    tokens_file = os.path.join(config['token_dir'], 'tokens.json')
    if not os.path.exists(tokens_file):
        with open(tokens_file, 'w') as f:
            f.write('{}')
        print(f"✓ Created {tokens_file}")
    
    # Summary
    print()
    print("=" * 70)
    print("SETUP COMPLETE!")
    print("=" * 70)
    print()
    print("Generated files:")
    print("  - config.toml (DO NOT commit to git!)")
    print("  - android-api.service")
    print("  - android-api.conf")
    print()
    print("Next steps:")
    print("  1. Review config.toml and adjust if needed")
    print("  2. Install Python dependencies: pip install -r requirements.txt")
    print("  3. Install systemd service (as root):")
    print(f"     sudo cp android-api.service /etc/systemd/system/")
    print(f"     sudo systemctl daemon-reload")
    print(f"     sudo systemctl enable android-api")
    print(f"     sudo systemctl start android-api")
    print("  4. Install Apache config (as root):")
    print(f"     sudo cp android-api.conf {config['apache_conf_dir']}/")
    print(f"     sudo systemctl restart httpd")
    print("  5. Generate student tokens:")
    print(f"     python scripts/generate_tokens.py bulk students.txt")
    print()
    print("IMPORTANT: config.toml is in .gitignore - do not commit it!")
    print()

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nSetup cancelled.")
        sys.exit(1)
